{"name": "登录异常，测试数据是:{'accounts': '', 'pwd': 'yaoyao', 'exp': '登录账号有误'}", "status": "passed", "parameters": [{"name": "args", "value": "{'accounts': '', 'pwd': 'yaoyao', 'exp': '登录账号有误'}"}], "start": 1599053412172, "stop": 1599053412287, "uuid": "e20f31dc-544c-4223-9fa2-2d24e86dbc4e", "historyId": "ff1d27090ef74452512974d50f385b0f", "testCaseId": "acfd50c72596b11b4392c40d7652bccf", "fullName": "script.test_login.TestLogin#test_login_error", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "LAPTOP-60EEKMHU"}, {"name": "thread", "value": "14368-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}